//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipment_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public equipment_master()
        {
            this.equipment_master1 = new HashSet<equipment_master>();
        }
    
        public long Tranx_Id { get; set; }
        public string EquipmentPartId { get; set; }
        public string Description { get; set; }
        public string ParentEquipmentPartId { get; set; }
        public string EquipmentType { get; set; }
        public string Compartment { get; set; }
        public Nullable<bool> IsPhysical { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTs { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> ChangedTs { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<equipment_master> equipment_master1 { get; set; }
        public virtual equipment_master equipment_master2 { get; set; }
    }
}
